param(
    [Parameter(Mandatory = $true)][string]$DockerDir,
    [Parameter(Mandatory = $true)][string]$Backend,
    [string]$RootDir = ''
)

. (Join-Path $PSScriptRoot 'rocm-probe.ps1')

$OverrideFile = 'docker-compose.rocm-runtime.generated.yml'
$OutPath = Join-Path $DockerDir $OverrideFile
$RocmWslStagingRel = './volumes/rocm-wsl'

if ([string]::IsNullOrWhiteSpace($RootDir)) {
    $RootDir = Split-Path -Parent $PSScriptRoot
}

function Write-RocmLog([string]$Message) {
    Write-Host "[guideants] $Message"
}

function Write-RocmWarn([string]$Message) {
    Write-Host "[guideants][warn] $Message"
}

function Write-Utf8NoBomFile {
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)][string[]]$Content
    )
    $encoding = New-Object System.Text.UTF8Encoding $false
    [System.IO.File]::WriteAllLines($Path, $Content, $encoding)
}

function Stage-WslRocmLibs {
    param([Parameter(Mandatory = $true)][string]$DockerDir)

    $source = Resolve-WslRocmLibrocdxgSource
    if ($null -eq $source) { return $null }

    $stagingLib = Join-Path $DockerDir 'volumes/rocm-wsl/lib'
    $stagingShare = Join-Path $DockerDir 'volumes/rocm-wsl/share'
    $stagingPath = Join-Path $stagingLib 'librocdxg.so'
    New-Item -ItemType Directory -Force -Path $stagingLib | Out-Null

    if (Test-NeedsRocmLibStage -StagingPath $stagingPath -SourceDistro $source.Distro -SourceLinuxPath $source.LinuxPath) {
        $wslStagingLib = ConvertTo-WslLinuxPath -Path $stagingLib
        $copyProbe = "cp -L '$($source.LinuxPath)' '$wslStagingLib/librocdxg.so'"
        & wsl.exe -d $source.Distro sh -lc $copyProbe 2>$null
        if ($LASTEXITCODE -ne 0 -or -not (Test-Path -LiteralPath $stagingPath)) {
            Write-RocmWarn "ROCm WSL: failed to stage librocdxg to $stagingLib"
            return $null
        }
        Write-RocmLog "ROCm WSL: staged librocdxg from $($source.Distro):$($source.LinuxPath)"
    }

    $result = @{
        LibRocdxg = "$RocmWslStagingRel/lib/librocdxg.so"
        Dids = ''
    }

    $didsSource = Resolve-WslRocmDidsSource
    if ($null -ne $didsSource) {
        $didsStaging = Join-Path $stagingShare 'dids.conf'
        $needsDids = -not (Test-Path -LiteralPath $didsStaging)
        if (-not $needsDids) {
            $srcDidsHash = Invoke-WslDistroProbe -Probe "md5sum -b '$($didsSource.LinuxPath)' 2>/dev/null | awk '{print `$1}'" -Distro $didsSource.Distro
            if (-not [string]::IsNullOrWhiteSpace($srcDidsHash)) {
                $dstDidsHash = (Get-FileHash -LiteralPath $didsStaging -Algorithm MD5).Hash.ToLowerInvariant()
                $needsDids = ($srcDidsHash.ToLowerInvariant() -ne $dstDidsHash)
            }
        }
        if ($needsDids) {
            New-Item -ItemType Directory -Force -Path $stagingShare | Out-Null
            $wslStagingShare = ConvertTo-WslLinuxPath -Path $stagingShare
            $didsCopyProbe = "cp '$($didsSource.LinuxPath)' '$wslStagingShare/dids.conf'"
            & wsl.exe -d $didsSource.Distro sh -lc $didsCopyProbe 2>$null | Out-Null
        }
        if (Test-Path -LiteralPath $didsStaging) {
            $result.Dids = "$RocmWslStagingRel/share/dids.conf"
        }
    }

    return $result
}

function Test-RocmWslMode {
    $dockerOs = (& docker info --format '{{.OperatingSystem}}' 2>$null | Select-Object -First 1)
    if ([string]$dockerOs -match 'Docker Desktop') { return $true }
    if ($env:WSL_DISTRO_NAME -and (Test-Path -LiteralPath '/dev/dxg')) { return $true }
    return $false
}

function Get-RocmNativeServiceLines([string]$ServiceName) {
    return @(
        "  ${ServiceName}:",
        '    devices:',
        '      - /dev/kfd',
        '      - /dev/dri',
        '    group_add:',
        '      - video',
        '      - render'
    )
}

function Write-RocmNativeOverride([string]$Path) {
    $lines = @(
        '# Generated by GuideAnts launcher - native Linux ROCm devices. Do not edit.',
        'services:'
    ) + (Get-RocmNativeServiceLines 'guideants-ai') + (Get-RocmNativeServiceLines 'docling-serve')
    Write-Utf8NoBomFile -Path $Path -Content $lines
}

function Get-RocmWslServiceLines {
    param(
        [string]$ServiceName,
        [string]$LibDxCore,
        [string]$LibRocdxg,
        [string]$Dids = ''
    )

    $lines = @(
        "  ${ServiceName}:",
        '    devices:',
        '      - /dev/dxg',
        '    cap_add:',
        '      - SYS_PTRACE',
        '    security_opt:',
        '      - seccomp:unconfined',
        '    environment:',
        '      - HSA_ENABLE_DXG_DETECTION=1',
        '    volumes:',
        '      - type: bind',
        "        source: $LibDxCore",
        '        target: /usr/lib/libdxcore.so',
        '        read_only: true',
        '      - type: bind',
        "        source: $LibRocdxg",
        '        target: /lib/librocdxg.so',
        '        read_only: true',
        '      - type: bind',
        "        source: $LibRocdxg",
        '        target: /usr/lib/librocdxg.so',
        '        read_only: true'
    )
    if (-not [string]::IsNullOrWhiteSpace($Dids)) {
        $lines += @(
            '      - type: bind',
            "        source: $Dids",
            '        target: /usr/share/rocdxg/dids.conf',
            '        read_only: true'
        )
    }
    return $lines
}

function Write-RocmWslOverride {
    param(
        [string]$Path,
        [string]$LibDxCore,
        [string]$LibRocdxg,
        [string]$Dids = ''
    )
    $lines = @(
        '# Generated by GuideAnts launcher - WSL ROCDXG binds. Do not edit.',
        'services:'
    ) + (Get-RocmWslServiceLines 'guideants-ai' $LibDxCore $LibRocdxg $Dids) + (Get-RocmWslServiceLines 'docling-serve' $LibDxCore $LibRocdxg $Dids)
    Write-Utf8NoBomFile -Path $Path -Content $lines
}

if (Test-Path -LiteralPath $OutPath) {
    Remove-Item -LiteralPath $OutPath -Force
}

if ($Backend -ne 'rocm') {
    return
}

if (Test-RocmWslMode) {
    $libDxCore = '/usr/lib/wsl/lib/libdxcore.so'
    $staged = Stage-WslRocmLibs -DockerDir $DockerDir

    if ($null -eq $staged) {
        if ($env:WSL_DISTRO_NAME) {
            foreach ($candidate in @('/opt/rocm/lib/librocdxg.so', '/opt/rocm-7.2.4/lib/librocdxg.so', '/opt/rocm-7.2.1/lib/librocdxg.so', '/opt/rocm-7.2.0/lib/librocdxg.so')) {
                if (Test-Path -LiteralPath $candidate) {
                    $staged = @{
                        LibRocdxg = $candidate
                        Dids = ''
                    }
                    foreach ($didsCandidate in @('/opt/rocm/share/rocdxg/dids.conf', '/usr/share/rocdxg/dids.conf')) {
                        if (Test-Path -LiteralPath $didsCandidate) {
                            $staged.Dids = $didsCandidate
                            break
                        }
                    }
                    break
                }
            }
        }
    }

    if ($null -eq $staged -or [string]::IsNullOrWhiteSpace($staged.LibRocdxg)) {
        Write-RocmInstallHint -RootDir $RootDir -WarnFn ${function:Write-RocmWarn}
        return
    }

    Write-RocmWslOverride -Path $OutPath -LibDxCore $libDxCore -LibRocdxg $staged.LibRocdxg -Dids $staged.Dids
    Write-RocmLog 'ROCm: WSL ROCDXG (/dev/dxg + staged librocdxg binds).'
}
else {
    Write-RocmNativeOverride -Path $OutPath
    Write-RocmLog 'ROCm: native Linux (/dev/kfd + /dev/dri).'
}
