#!/usr/bin/env bash

# Configure ROCm container runtime for native Linux or WSL ROCDXG.
# Usage: source this file, then: select_rocm_runtime "$DOCKER_DIR" "$ROOT_DIR"

ROCM_RUNTIME_OVERRIDE_FILE="${ROCM_RUNTIME_OVERRIDE_FILE:-docker-compose.rocm-runtime.generated.yml}"
ROCM_WSL_STAGING_REL="./volumes/rocm-wsl"

# shellcheck source=rocm-probe.sh
. "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/rocm-probe.sh"

is_rocm_wsl_mode() {
  if docker info --format '{{.OperatingSystem}}' 2>/dev/null | grep -q 'Docker Desktop'; then
    return 0
  fi
  if grep -qiE 'microsoft|wsl' /proc/version 2>/dev/null && [[ -e /dev/dxg ]]; then
    return 0
  fi
  return 1
}

resolve_rocm_librocdxg_host_path() {
  local p
  for p in /opt/rocm/lib/librocdxg.so /opt/rocm-7.2.4/lib/librocdxg.so /opt/rocm-7.2.1/lib/librocdxg.so /opt/rocm-7.2.0/lib/librocdxg.so; do
    if [[ -f "$p" ]]; then
      readlink -f "$p" 2>/dev/null || realpath "$p" 2>/dev/null || echo "$p"
      return 0
    fi
  done
  return 1
}

resolve_rocm_dids_host_path() {
  local p
  for p in /opt/rocm/share/rocdxg/dids.conf /usr/share/rocdxg/dids.conf; do
    if [[ -f "$p" ]]; then
      echo "$p"
      return 0
    fi
  done
  return 1
}

needs_rocm_lib_stage() {
  local staging_path="$1" src_path="$2"
  [[ -f "$staging_path" ]] || return 0
  local src_hash dst_hash
  src_hash="$(md5sum -b "$src_path" 2>/dev/null | awk '{print $1}' || true)"
  [[ -n "$src_hash" ]] || return 0
  dst_hash="$(md5sum -b "$staging_path" 2>/dev/null | awk '{print $1}' || true)"
  [[ "$src_hash" != "$dst_hash" ]]
}

stage_rocm_wsl_libs_for_compose() {
  local docker_dir="$1"
  local staging_lib="$docker_dir/volumes/rocm-wsl/lib"
  local staging_share="$docker_dir/volumes/rocm-wsl/share"
  local src dids_src

  src="$(resolve_rocm_librocdxg_host_path)" || return 1
  mkdir -p "$staging_lib"

  if needs_rocm_lib_stage "$staging_lib/librocdxg.so" "$src"; then
    cp -L "$src" "$staging_lib/librocdxg.so"
  fi

  dids_src="$(resolve_rocm_dids_host_path)" || dids_src=""
  if [[ -n "$dids_src" ]]; then
    mkdir -p "$staging_share"
    if needs_rocm_lib_stage "$staging_share/dids.conf" "$dids_src"; then
      cp "$dids_src" "$staging_share/dids.conf"
    fi
  fi

  return 0
}

write_rocm_native_override() {
  local out="$1"
  cat >"$out" <<'EOF'
# Generated by GuideAnts launcher - native Linux ROCm devices. Do not edit.
services:
  guideants-ai:
    devices:
      - /dev/kfd
      - /dev/dri
    group_add:
      - video
      - render
  docling-serve:
    devices:
      - /dev/kfd
      - /dev/dri
    group_add:
      - video
      - render
EOF
}

append_rocm_wsl_service_block() {
  local service_name="$1"
  local libdxcore="$2"
  local librocdxg="$3"
  local dids="${4:-}"
  cat <<EOF
  ${service_name}:
    devices:
      - /dev/dxg
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    environment:
      - HSA_ENABLE_DXG_DETECTION=1
    volumes:
      - type: bind
        source: ${libdxcore}
        target: /usr/lib/libdxcore.so
        read_only: true
      - type: bind
        source: ${librocdxg}
        target: /lib/librocdxg.so
        read_only: true
      - type: bind
        source: ${librocdxg}
        target: /usr/lib/librocdxg.so
        read_only: true
EOF
  if [[ -n "$dids" ]]; then
    cat <<EOF
      - type: bind
        source: ${dids}
        target: /usr/share/rocdxg/dids.conf
        read_only: true
EOF
  fi
}

write_rocm_wsl_override() {
  local out="$1"
  local libdxcore="$2"
  local librocdxg="$3"
  local dids="${4:-}"
  {
    cat <<'EOF'
# Generated by GuideAnts launcher - WSL ROCDXG binds. Do not edit.
services:
EOF
    append_rocm_wsl_service_block "guideants-ai" "$libdxcore" "$librocdxg" "$dids"
    append_rocm_wsl_service_block "docling-serve" "$libdxcore" "$librocdxg" "$dids"
  } >"$out"
}

select_rocm_runtime() {
  local docker_dir="${1:-.}"
  local root_dir="${2:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
  local backend="${SELECTED_BACKEND:-}"
  local out="$docker_dir/$ROCM_RUNTIME_OVERRIDE_FILE"
  local log_fn="${ROCM_RUNTIME_LOG_FN:-log}"
  local warn_fn="${ROCM_RUNTIME_WARN_FN:-warn}"

  rm -f "$out"
  [[ "$backend" == "rocm" ]] || return 0

  if is_rocm_wsl_mode; then
    local libdxcore="/usr/lib/wsl/lib/libdxcore.so"
    local librocdxg dids

    if docker info --format '{{.OperatingSystem}}' 2>/dev/null | grep -q 'Docker Desktop'; then
      if stage_rocm_wsl_libs_for_compose "$docker_dir"; then
        librocdxg="${ROCM_WSL_STAGING_REL}/lib/librocdxg.so"
        if [[ -f "$docker_dir/volumes/rocm-wsl/share/dids.conf" ]]; then
          dids="${ROCM_WSL_STAGING_REL}/share/dids.conf"
        else
          dids=""
        fi
      else
        librocdxg=""
        dids=""
      fi
    else
      librocdxg="$(resolve_rocm_librocdxg_host_path)" || librocdxg=""
      dids="$(resolve_rocm_dids_host_path)" || dids=""
    fi

    if [[ -z "$librocdxg" ]]; then
      "$warn_fn" "ROCm WSL: librocdxg not found."
      "$warn_fn" "Install ROCm in WSL with:"
      "$warn_fn" "  $(rocm_install_command_hint "$root_dir")"
      "$warn_fn" "Or run: ./guideants.sh --install-rocm-wsl (from Git Bash/WSL on Windows)"
      return 0
    fi

    write_rocm_wsl_override "$out" "$libdxcore" "$librocdxg" "$dids"
    "$log_fn" "ROCm: WSL ROCDXG (/dev/dxg + librocdxg binds)."
  else
    write_rocm_native_override "$out"
    "$log_fn" "ROCm: native Linux (/dev/kfd + /dev/dri)."
  fi
}
