// GuideAnts Azure infrastructure (Phase 1) — no container apps
// Deploys to resource group scope (compatible with AZBuilder role)
targetScope = 'resourceGroup'

@description('Environment name (dev, staging, prod)')
param environmentName string = 'dev'

@description('Location for all resources')
param location string = 'East US 2'

@description('Container Apps Environment name')
param containerAppsEnvironmentName string = 'cae-guideants-${environmentName}'

@description('Application name prefix')
param appNamePrefix string = 'guideants'

@description('SQL database name')
param sqlDatabaseName string = 'guideants'

@description('SQL Admin password')
@secure()
param sqlAdminPassword string

@description('SQL AAD Admin Object ID (optional, for deployer migrations)')
param sqlAadAdminObjectId string = ''

@description('Deployer object ID for Key Vault secret updates during/after deploy')
param deployerObjectId string = ''

@description('JWT signing key (generated by generate-secrets script)')
@secure()
param jwtSigningKey string

@description('SettingsSecrets AES key (base64, generated by generate-secrets)')
@secure()
param settingsSecretsKey string

@description('Script execution agent token')
@secure()
param scriptAgentToken string

@description('Script execution admin token')
@secure()
param scriptAgentAdminToken string

@description('DocumentServer JWT secret')
@secure()
param documentServerJwtSecret string

var tags = {
  environment: environmentName
  project: 'guideants'
  deployedBy: 'bicep'
  profile: 'azure-slim'
}

module coreInfrastructure 'modules/core-infrastructure.bicep' = {
  name: 'core-infrastructure'
  params: {
    location: location
    environmentName: environmentName
    appNamePrefix: appNamePrefix
    tags: tags
  }
}

module containerAppsIdentity 'modules/container-apps-identity.bicep' = {
  name: 'container-apps-identity'
  params: {
    location: location
    environmentName: environmentName
    appNamePrefix: appNamePrefix
    tags: tags
  }
}

module keyVault 'modules/key-vault.bicep' = {
  name: 'key-vault'
  params: {
    location: location
    environmentName: environmentName
    appNamePrefix: appNamePrefix
    sqlDatabaseName: sqlDatabaseName
    sqlAdminPassword: sqlAdminPassword
    jwtSigningKey: jwtSigningKey
    settingsSecretsKey: settingsSecretsKey
    scriptAgentToken: scriptAgentToken
    scriptAgentAdminToken: scriptAgentAdminToken
    documentServerJwtSecret: documentServerJwtSecret
    deployerObjectId: deployerObjectId
    containerAppsPrincipalId: containerAppsIdentity.outputs.principalId
    tags: tags
  }
}

module storage 'modules/storage.bicep' = {
  name: 'storage'
  params: {
    location: location
    environmentName: environmentName
    appNamePrefix: appNamePrefix
    tags: tags
  }
}

module database 'modules/database.bicep' = {
  name: 'database'
  params: {
    location: location
    environmentName: environmentName
    appNamePrefix: appNamePrefix
    sqlAdminPassword: sqlAdminPassword
    sqlAadAdminObjectId: sqlAadAdminObjectId
    sqlDatabaseName: sqlDatabaseName
    tags: tags
  }
}

module containerAppsEnvironment 'modules/container-apps-environment.bicep' = {
  name: 'container-apps-environment'
  params: {
    location: location
    containerAppsEnvironmentName: containerAppsEnvironmentName
    containerAppsSubnetId: coreInfrastructure.outputs.containerAppsSubnetId
    tags: tags
  }
}

output containerAppsEnvironmentId string = containerAppsEnvironment.outputs.containerAppsEnvironmentId
output containerAppsEnvironmentName string = containerAppsEnvironment.outputs.containerAppsEnvironmentName
output containerAppsEnvironmentDefaultDomain string = containerAppsEnvironment.outputs.containerAppsEnvironmentDefaultDomain
output keyVaultName string = keyVault.outputs.keyVaultName
output keyVaultUri string = keyVault.outputs.keyVaultUri
output storageAccountName string = storage.outputs.storageAccountName
output sqlServerFqdn string = database.outputs.sqlServerFqdn
output sqlServerName string = database.outputs.sqlServerName
output sqlDatabaseName string = database.outputs.sqlDatabaseName
output appInsightsConnectionString string = coreInfrastructure.outputs.appInsightsConnectionString
